### ISSUE TITLE
Solar pressure stuck at 250 bar

### ISSUE THREAD

**Issue by moster11** [Lurchi70/ha-solvis-heating#2]
All values in my configuration are reporting their values finely - only "Solvis Remote Solar Pressure" is stuck at 250 bar from the installation on. 250 seems to be the maximum value and is only reported when the value is missing in the system. Is it possible this value just does not exist in my configuration or is it a fault in the integration?

![grafik](https://user-images.githubusercontent.com/65911580/236923798-5d4fe14c-02e2-4b4c-91ef-d3ac866b7c09.png)

**Comment by Lurchi70** [comment]
I know this issue. My value is stuck stuck at -35 bar. I assume, that the sensor is not build in the system and just does not provide a value. (I've checked my Solvis Hardware and the schematics - and did not find such a sensor...
I would ask you the ignore this value. There is actually no way to identify this automatically. 
I'll close this issue - if you have additional ideas how to improve this code, let me know.
